image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - create_infra
  - deploy
  - review
  - stage
  - production
  - clear_infra

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  CI_SHORT_COMMIT_SHA: '$${CI_COMMIT_SHA:0:8}'
  DOCKER_IMAGE: '${CI_COMMIT_REF_NAME}:1.0'
  DOCKER_IP: '127.0.0.1'

build_job:
  stage: build
  before_script: 
    - cd reddit
    - echo CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME
    - echo DOCKER_IMAGE=$DOCKER_IMAGE
    - docker login -u $HUB_USER -p $HUB_PASS
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker tag $DOCKER_IMAGE $HUB_USER/$DOCKER_IMAGE
    - docker push $HUB_USER/$DOCKER_IMAGE

test_unit_job:
  stage: test
  image:
    name: $HUB_USER/$DOCKER_IMAGE
  script:
    - echo DOCKER_IMAGE=$DOCKER_IMAGE
    - cd /reddit
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

create_infra_job:
  stage: create_infra
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - cd gitlab-ci/infra/terraform 
    - rm -rf .terraform
    - terraform --version
    - mkdir -p ./credentials
    - echo $SERVICEACCOUNT | base64 -d > ./credentials/project.json
    - mv terraform.tfvars.example terraform.tfvars
    - echo CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME
    - export TF_VAR_vm_name=$CI_COMMIT_REF_NAME
    - terraform init
    - terraform destroy -auto-approve
  script:
    - terraform validate
    - terraform plan -out "planfile"
    - terraform apply -input=false "planfile"

deploy_dev_job:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - echo VM_IP=$VM_IP
    - cd gitlab-ci/infra/terraform
    - mkdir -p ./credentials
    - echo $SERVICEACCOUNT | base64 -d > ./credentials/project.json
    - mv terraform.tfvars.example terraform.tfvars
    - terraform init
    - eval export DOCKER_IP=$(terraform output docker_external_ip)
    - echo DOCKER_IP=$DOCKER_IP
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo $TF_VAR_public_key_path > ~/.ssh/appuser.pub
    - chmod 644 ~/.ssh/appuser.pub
    - echo $TF_VAR_private_key_path > ~/.ssh/appuser
    - chmod 600 ~/.ssh/appuser
    - cat ~/.ssh/appuser
  script:
    - echo 'Deploy'
    - ssh appuser@$DOCKER_IP -o StrictHostKeyChecking=no -i ~/.ssh/appuser -vvv 'sudo docker run -d -p 9292:9292 $HUB_USER/$DOCKER_IMAGE'
  environment:
    name: dev
    url: http://dev.example.com

branch_review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$DOCKER_IP:9292
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com

clear_infra:
  stage: clear_infra
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  when: manual
  before_script:
    - cd gitlab-ci/infra/terraform
    - mkdir -p ./credentials
    - echo $SERVICEACCOUNT | base64 -d > ./credentials/project.json
    - mv terraform.tfvars.example terraform.tfvars
  script:
    - terraform init
    - terraform destroy -auto-approve
