version: '3.5'
services:

  post_db:
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
         aliases:
           - mongodb
           - post_db
           - comment_db

  ui:
    image: ${USER_NAME}/ui:${UI_SERVICE_VERSION}
    ports:
      - ${UI_PUBLICATION_PORT}:9292/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${POST_SERVICE_VERSION}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
   

  comment:
    image: ${USER_NAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  back_net:
    name: back_net
    ipam:
      config:
      - subnet: 10.0.2.0/24
  front_net:
    name: front_net
    ipam:
      config:
      - subnet: 10.0.1.0/24
