version: '3.5'
services:
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      front_net:
        aliases:
          - prometheus
      back_net:
        aliases:
          - prometheus
  
  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      front_net:
        aliases:
          - cadvisor
      back_net:
        aliases:
          - cadvisor
  
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      front_net:
        aliases:
          - node-exporter
      back_net:
        aliases:
          - node-exporter
    
  mongodb_exporter:
    image: rimskiy/mongodb_exporter:latest
    user: root
    command:
      - '-mongodb.uri=mongodb://mongodb:27017'
      - '-web.listen-address=mongodb-exporter:9104'
    networks:
      back_net:
        aliases:
          - mongodb-exporter
  
  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    user: root
    ports:
      - '9115:9115'
    networks:
      front_net:
        aliases:
          - blackbox-exporter
      back_net:
        aliases:
          - blackbox-exporter

volumes:
  prometheus_data:

networks:
  front_net:
    external: true
  back_net:
    external: true

