version: '3.5'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      front_net:
      back_net:

  elasticsearch:
    image: elasticsearch:6.5.4
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      front_net:
        aliases:
          - elasticsearch
      back_net:
        aliases:
          - elasticsearch

  kibana:
    image: kibana:6.5.4
    ports:
      - "5601:5601"
    networks:
      front_net:
        aliases:
          - kibana
      back_net:
        aliases:
          - kibana
networks:
  back_net:
    name: back_net
    ipam:
      config:
      - subnet: 10.0.2.0/24
  front_net:
    name: front_net
    ipam:
      config:
      - subnet: 10.0.1.0/24
